version: '3'

# Each service runs in a seperate container
services:
    # the name of the service
    express-service:
        # shorthand name for the container
        container_name: restful-fullstack
        
        # build path to the Dockerfile
        build: .
        
        # create a bind mount so local changes show up in the container
        # for development (lots of changes - restarting the container would be slow)
        volumes:
            - ./:/app:Z 
        
        # map the ports <outside container>:<inside container>
        ports:
            - "8000:8000"
            
        # make sure the postgres-FullStack service starts first
        depends_on:
            - postgres-FullStack
        
        # makes the value "postgres-FullStack" available in process.env.DATABASE_HOST in Node server, 
        # so Pool connects to the container instead of localhost
        environment:
            DATABASE_HOST: "postgres-FullStack"

        # Override the entrypoint in the Dockerfile
        command: ["nodemon", "fullstack.js"]


    postgres-FullStack:
        container_name: postgres-FullStack
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: postgres-FullStack
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
            POSTGRES-FullStack: FullStack 
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - pgdatasource:/var/lib/postgresql/data



    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: javaneyt@icloud.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-FullStack
        
volumes:
  pgdatasource:
  pgadmin-data:

networks:
  default:
